default['naviserver']['version_full']   = "4.99.4d"
default['naviserver']['version']        = "4.99.4"
default['naviserver']['install_prefix'] = "/opt"
default['naviserver']['bind_to']        = "127.0.0.1:8080"
default['naviserver']['run_user']       = "nobody"
